import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '../styles/css/globals.css'
import React from 'react'
import NabBar from '@/components/layout/NavBar'
import { Toaster } from '@/components/ui/toaster'

const geistSans = localFont({
    src: './../styles/fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
})
const geistMono = localFont({
    src: './../styles/fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
})

export const metadata: Metadata = {
    title: 'untitled',
    description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <NabBar />
                <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
                    {children}
                </div>
                <Toaster />
            </body>
        </html>
    )
}
